# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        selectorThumbail: 
            quality : 75
            filters:
                scale : 
                    dim : [120, 120]
        miniThumbail: 
            quality : 75
            filters:
                scale : 
                    dim : [70, 70]
        quote: 
            quality : 75
            filters:
                scale : 
                    dim : [100, 100]
        timeTableMedia:
            quality : 100
            filters :
                thumbnail : 
                    size : [390, 510]
                    mode : outbound
        activisu:
            filters:
                fixed:
                    width: 120
                    height: 300
        carousel:
            filters:
                fixed:
                    width: 800
                    height: 600
        certif:
            filters:
                scale: 
                    dim : [150, 150]
        contact:
            filters:
                fixed:
                    width: 1000
                    height: 800
        socialNetwork:
            filters:
                fixed:
                    width: 50
                    height: 50
        logo: 
            quality : 100
            filters:
                scale : 
                    dim : [250, 250]
        cover: 
            quality : 100
            filters:
                fixed:
                    width: 1920
                    height: 900