vich_uploader:
    db_driver: orm

    mappings:
        media:
            uri_prefix: /img/media
            upload_destination: '%kernel.project_dir%/public/img/media'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
